<h1>Inscription</h1>

<form action="logic/register.php" method="POST">
    <fieldset>
        <legend>Mes informations personelles : </legend>

        <div>
            <label for="first_name">Prénom :</label>
            <input type="text" id="first_name" name="first_name" required>
        </div>

        <div>
            <label for="last_name">Nom :</label>
            <input type="text" id="last_name" name="last_name" required>
        </div>

        <div>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
        </div>

        <div>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>
        </div>
    </fieldset>

    <div>
        <button type="submit">S'inscrire</button>
    </div>
</form>
